### ISSUE TITLE
need to add documentation

### ISSUE THREAD

**Issue by DSDmark** [DSDmark/SimpleWeb#11]
need to add documentation in learn.md file

**Comment by theavitw** [comment]
Hey I am looking forward to contribute on this project. Tell me more about this issue.

**Comment by DSDmark** [comment]
Hi @theavitw,

Happy to have you here, concerning the contribution, you can begin by writing the documentation for this repository, and if you believe there is anything that needs to be improved, you can suggest it, or you can fork that repository and enhance it. Any form of work will be valued if it is accurate and thorough. 

Here is some information to assist you with your work: 

[**How to write markdown**](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
